# Datos de la clasificación, cap. 5 (Taddhita, §344–§405). Claude, 2026-10-01.
# Se ejecuta una vez para volcar en recursos/clasificacion/datos.json.
# ATENCIÓN: §400 y §405 se revisaron después directamente en datos.json (2026-10-01: §405 paribhāsā por Rū 364 y Nyāsa al §2). No volver a ejecutar sin incorporar esos cambios.
import json, unicodedata, re
N=lambda s: unicodedata.normalize('NFC',s)
P='recursos/clasificacion/datos.json'
D=json.load(open(P,encoding='utf-8')); S=D['suttas']
RUJ=json.load(open('docs/capitulo-5/_ru_cap5.json',encoding='utf-8'))
RU_OTROS={253:'Dvi eka aṭṭha icc etesam anto ākāro hoti vā saṅkhyāne uttarapade pare. Vavatthitavibhāsā ’yaṃ',
 254:'Ekādito saṅkhyāto parassa dasassa ādissa dassa rakāro hoti vā saṅkhyāne',
 255:'Vīsati dasa icc etesu paresu dvisaddassa bā hoti vā. Tusaddena tiṃsāyam pi',
 256:'Gaṇane dasass’ ādimhi ṭhitassa catu icc etassa upapadassa tusaddo lopo hoti, uttarapadādimhi ṭhitassa catūpapadassa cakārassa cu-co-ādesā honti navā',
 257:'Cha icc etassa saṅkhyāsaddassa niccaṃ so hoti dase pare',
 258:'Saṅkhyānaṃ dakāra-rakārānaṃ lakārādeso hoti vā … Vavatthitavibhāsattho ’yaṃ vāsaddo, tena “soḷasa” iti niccaṃ',
 259:'Aṭṭhādito ca dasasaddassa dakārassa rakāro hoti vā saṅkhyāne',
 68:'Sarūpānaṃ samānarūpānaṃ padabyañjanānaṃ majjhe eko ’va sissate, aññe lopam āpajjante asakin ti ekaseso',
 354:'Kvaci taddhita-samāsa-nāmopasaggādīsu padesu ādi-majjh’-uttarabhūtānaṃ sarānaṃ jinavacanānuparodhena dīgha-rassā honti paccayesu, apaccayesu paresu, aparabhūtesu ca'}
EXTRA={365:' … Puna vuddhiggahaṇaṃ “negamajānapadā” ti ādīsu uttarapadavuddhibhāvatthaṃ',
 415:' … Iminā nipātanena yolopo',380:' … “Tā” ti yogavibhāgena sakatthe pi devo yeva devatā',
 381:' … Casaddena hitādiatthe pi', 398:' … Caggahaṇena so-ila-va-ālādippacayā ca',
 410:' … Apiggahaṇena aññatthā pi dvisaddassa du-ādeso hoti, casaddena di ca',
 387:' … tusaddaggahaṇena ttana-ṇeyyādippaccayā ca', 420:' … Casaddena eka-dvito jjha ca, suttādito so ca',
 421:' … tusaddena thattāpaccayo ca'}
def ru_txt(r):
    if r==0: return ('— (este sutta no tiene número en Rūpasiddhi).','— (this sutta has no number in the Rūpasiddhi).')
    t=RU_OTROS.get(r) or RUJ[str(r)]
    if r not in RU_OTROS:
        t=re.split(r'(?<=[a-zāīūṃ])\. ',t)[0].rstrip('.')
    t=t+EXTRA.get(r,'')
    return (f'Rū {r}: «{t}».', f'Rū {r}: “{t}”.')
RU={344:361,345:366,346:367,347:368,348:371,349:372,350:373,351:374,352:376,353:378,354:379,355:380,356:381,357:382,358:383,359:384,360:387,361:388,362:389,363:390,364:398,365:399,366:400,367:401,368:402,369:403,370:405,371:404,372:385,373:406,374:408,375:412,376:257,377:0,378:414,379:258,380:255,381:254,382:259,383:253,384:407,385:409,386:410,387:411,388:68,389:413,390:256,391:423,392:418,393:415,394:416,395:417,396:363,397:420,398:421,399:422,400:364,401:375,402:377,403:354,404:370,405:365}
APA_ES='en el significado de «descendiente de él» (tass’ āpaccaṃ)'; APA_EN='in the sense of “his descendant” (tass’ āpaccaṃ)'
TA_ES='en el significado de «hay esto de él» (tad ass’ atthi)'; TA_EN='in the sense of “he has this” (tad ass’ atthi)'
R={}
NOTAS={}
R.update({
344:('V','paccaya',f'Opcionalmente, aplicación del sufijo ‘ṇa’ {APA_ES}.',f'Optionally, application of the suffix ‘ṇa’ {APA_EN}.','apaccatthe vikappena ṇapaccayo hotī ti ñāpanatthaṃ'),
345:('V','paccaya',f'Opcionalmente, aplicación de los sufijos ‘ṇāyana’ y ‘ṇāna’ tras “Vaccha” y otros nombres de linaje, {APA_ES}.',f'Optionally, application of the suffixes ‘ṇāyana’ and ‘ṇāna’ after “Vaccha” and other clan names, {APA_EN}.','tasmā Vacchādito saddagaṇato ṇāyana-ṇānapaccayā honti “tassa apaccan” ty atthe vikappenā ti ñāpanatthaṃ'),
346:('V','paccaya',f'Opcionalmente, aplicación del sufijo ‘ṇeyya’ tras “Kattikā” y otros, {APA_ES}.',f'Optionally, application of the suffix ‘ṇeyya’ after “Kattikā” and others, {APA_EN}.','tehi Kattikādīhi “tassāpaccan” ty atthe ṇeyyapaccayo hoti vikappenā ti ñāpanatthaṃ'),
347:('V','paccaya',f'Opcionalmente, aplicación del sufijo ‘ṇi’ tras una base en ‘a’, {APA_ES}.',f'Optionally, application of the suffix ‘ṇi’ after a base in ‘a’, {APA_EN}.','akārantato ṇipaccayo hoti “tassāpaccan” ty atthe vikappenā ti ñāpanatthaṃ'),
348:('V','paccaya',f'Opcionalmente, aplicación del sufijo ‘ṇava’ tras “Upaku” y otros, {APA_ES}.',f'Optionally, application of the suffix ‘ṇava’ after “Upaku” and others, {APA_EN}.','upaku icc evamādīhi “tassāpaccan” ty atthe ṇavapaccayo hoti vikappenā ti ñāpanatthaṃ'),
349:('V','paccaya',f'Opcionalmente, aplicación del sufijo ‘ṇera’ tras “vidhavā” y otros, {APA_ES}.',f'Optionally, application of the suffix ‘ṇera’ after “vidhavā” and others, {APA_EN}.','vidhavādito saddagaṇato ṇerapaccayo hoti “tassāpaccan” ty atthe vikappenā ti ñāpanatthaṃ'),
350:('V','paccaya','Opcionalmente, aplicación del sufijo ‘ṇika’ en los significados de «mezclado con eso», «cruza con eso», «va con eso» y «transporta con eso».','Optionally, application of the suffix ‘ṇika’ in the senses “mixed with that”, “crosses with that”, “goes with that” and “carries with that”.','yena vā saṃsaṭṭhaṃ, yena vā tarati, yena vā carati, yena vā vahatī ty atthe ṇikapaccayo hoti vikappenā ti ñāpanatthaṃ'),
351:('V','paccaya','Opcionalmente, aplicación del sufijo ‘ṇika’ en los significados de «estudia eso», «hecho con eso», etc., y de ubicación, ocupación, habilidad, mercancía y sustento.','Optionally, application of the suffix ‘ṇika’ in the senses “studies that”, “made with that”, etc., and of location, occupation, skill, wares and livelihood.','tam adhīte ty atthe ca tena katan ty ādy atthe ca … icc etesv atthesu ca ṇikapaccayo hoti vikappenā ti ñāpanatthaṃ'),
352:('V','paccaya','Opcionalmente, aplicación del sufijo ‘ṇa’ tras un nombre de tinte en el significado de «teñido con eso», y en «esto es de ese» y otros significados.','Optionally, application of the suffix ‘ṇa’ after a word for a dye in the sense “dyed with that”, and in “this is his” and other senses.','rāgatthamhā saddagaṇato ṇapaccayo hoti “tena rattaṃ”, “tass’ edan” ty atthesu ca aññatthesu ca vikappenā ti ñāpanatthaṃ'),
353:('V','paccaya','Aplicación de los sufijos ‘ima’ e ‘iya’ en el significado de “jāta” (nacido), etc.','Application of the suffixes ‘ima’ and ‘iya’ in the sense of “jāta” (born), etc.','jāta icc evamādīnam atthe ima iya icc ete paccayā hontī ti ñāpanatthaṃ'),
354:('V','paccaya','Aplicación de los sufijos ‘kaṇ’ y ‘ṇa’ en el significado de agregación.','Application of the suffixes ‘kaṇ’ and ‘ṇa’ in the sense of aggregation.','samūhatthe kaṇ ṇa icc ete paccayā hontī ti ñāpanatthaṃ'),
355:('V','paccaya','Aplicación del sufijo ‘tā’ tras “gāma”, “jana”, “bandhu”, “sahāya” y otros, en el significado de agregación.','Application of the suffix ‘tā’ after “gāma”, “jana”, “bandhu”, “sahāya” and others, in the sense of aggregation.','gāma-jana-bandhu-sahāya icc evamādīhi samūhatthe tāpaccayo hotī ti ñāpanatthaṃ'),
356:('V','paccaya','Aplicación del sufijo ‘iya’ en el significado de «esto es su causa» (tad assa ṭhānaṃ).','Application of the suffix ‘iya’ in the sense “this is its cause” (tad assa ṭhānaṃ).','“tad assa ṭhānan” ty atthe iyapaccayo hotī ti ñāpanatthaṃ … caggahaṇena hitādy atthe pi iyapaccayo hoti'),
357:('V','paccaya','Aplicación del sufijo ‘āyitatta’ en el significado de comparación.','Application of the suffix ‘āyitatta’ in the sense of comparison.','upamatthe āyitattapaccayo hotī ti ñāpanatthaṃ'),
358:('V','paccaya','Aplicación del sufijo ‘la’ en el significado de «depende de eso» (y de «esto es su causa»).','Application of the suffix ‘la’ in the sense “depends on that” (and “this is its cause”).','tannissitatthe lapaccayo hotī ti ñāpanatthaṃ'),
359:('V','paccaya','Aplicación del sufijo ‘ālu’ en el significado de abundancia de eso.','Application of the suffix ‘ālu’ in the sense of abundance of that.','tabbahulatthe ālupaccayo hotī ti ñāpanatthaṃ'),
360:('V','paccaya','Aplicación de los sufijos ‘ṇya’, ‘tta’ y ‘tā’ en el significado de estado.','Application of the suffixes ‘ṇya’, ‘tta’ and ‘tā’ in the sense of state.','ṇya tta tā icc ete paccayā honti bhāvatthe ti ñāpanatthaṃ'),
361:('V','paccaya','Aplicación del sufijo ‘ṇa’ tras “visama” y otros, en el significado de estado.','Application of the suffix ‘ṇa’ after “visama” and others, in the sense of state.','visama icc evamādīhi ṇapaccayo hoti bhāvatthe ti ñāpanatthaṃ'),
362:('V','paccaya','Aplicación del sufijo ‘kaṇ’ tras “ramaṇīya” y otros, en el significado de estado.','Application of the suffix ‘kaṇ’ after “ramaṇīya” and others, in the sense of state.','ramaṇīya icc evamādito kaṇpaccayo hoti bhāvatthe ti ñāpanatthaṃ'),
363:('V','paccaya','Aplicación de los sufijos ‘tara’, ‘tama’, ‘isika’, ‘iya’ e ‘iṭṭha’ en el significado de distinción.','Application of the suffixes ‘tara’, ‘tama’, ‘isika’, ‘iya’ and ‘iṭṭha’ in the sense of distinction.','visesatthe tara tama isika iya iṭṭha icc ete paccayā hontī ti ñāpanatthaṃ'),
364:('V','paccaya',f'Aplicación del sufijo ‘vī’ {TA_ES}.',f'Application of the suffix ‘vī’ {TA_EN}.','“tad ass’ atthī” ty atthe vīpaccayo hotī ti ñāpanatthaṃ'),
365:('V','paccaya',f'Aplicación del sufijo ‘sī’ tras “tapa” y otros, {TA_ES}.',f'Application of the suffix ‘sī’ after “tapa” and others, {TA_EN}.','tapa icc evamādito “tad ass’ atthī” ty atthe sīpaccayo hotī ti ñāpanatthaṃ'),
366:('V','paccaya',f'Aplicación de los sufijos ‘ika’ e ‘ī’ tras “daṇḍa” y otros, {TA_ES}.',f'Application of the suffixes ‘ika’ and ‘ī’ after “daṇḍa” and others, {TA_EN}.','daṇḍādito ika ī icc ete paccayā honti “tad ass’ atthī” ty atthe ti ñāpanatthaṃ'),
367:('V','paccaya',f'Aplicación del sufijo ‘ra’ tras “madhu” y otros, {TA_ES}.',f'Application of the suffix ‘ra’ after “madhu” and others, {TA_EN}.','madhvādito rapaccayo hoti “tad ass’ atthī” ty atthe ti ñāpanatthaṃ'),
368:('V','paccaya',f'Aplicación del sufijo ‘vantu’ tras “guṇa” y otros, {TA_ES}.',f'Application of the suffix ‘vantu’ after “guṇa” and others, {TA_EN}.','guṇa icc evamādito vantupaccayo hoti “tad ass’ atthī” ty atthe ti ñāpanatthaṃ'),
369:('V','paccaya',f'Aplicación del sufijo ‘mantu’ tras “sati” y otros, {TA_ES}.',f'Application of the suffix ‘mantu’ after “sati” and others, {TA_EN}.','satyādīhi mantupaccayo hoti “tad ass’ atthī” ty atthe ti ñāpanatthaṃ'),
370:('V','paccaya',f'Aplicación del sufijo ‘ṇa’ tras “saddhā” y otros, {TA_ES}.',f'Application of the suffix ‘ṇa’ after “saddhā” and others, {TA_EN}.','saddhādito ṇapaccayo hoti “tad ass’ atthī” ty atthe ti ñāpanatthaṃ'),
371:('V','ādesa','Sustitución de la ‘u’ final de “āyu” por ‘asa’ cuando sigue ‘mantu’ (āyasmā).','Substitution of the final ‘u’ of “āyu” by ‘asa’ when ‘mantu’ follows (āyasmā).','āyusaddassa ukārassa asādeso hoti mantumhī ti ñāpanatthaṃ'),
372:('V','paccaya','Aplicación del sufijo ‘maya’ en el significado de «hecho de eso» (tappakativacana).','Application of the suffix ‘maya’ in the sense “made of that” (tappakativacana).','tappakativacanatthe mayapaccayo hotī ti ñāpanatthaṃ'),
373:('V','paccaya','Aplicación del sufijo ‘ma’ en el significado de ordinal.','Application of the suffix ‘ma’ in the sense of an ordinal.','saṅkhyāpūraṇatthe mapaccayo hotī ti ñāpanatthaṃ'),
374:('V','ādesa','Opcionalmente, sustitución de “cha” por ‘sa’.','Optionally, substitution of “cha” by ‘sa’.','chasaddassa sakārādeso hoti vikappenā ti ñāpanatthaṃ'),
})
R.update({
375:('V','paccaya','Opcionalmente, aplicación del sufijo ‘ī’ al final de “dasa” tras “eka” y otros, en el significado de ordinal (ekādasī).','Optionally, application of the suffix ‘ī’ at the end of “dasa” after “eka” and others, in the sense of an ordinal (ekādasī).','ekādito dasassa ante īpaccayo hoti saṅkhyāpūraṇatthe vikappenā ti ñāpanatthaṃ'),
376:('V','ādesa','Sustitución de “cha” por ‘so’, siempre, cuando sigue “dasa” (soḷasa).','Substitution of “cha” by ‘so’, always, when “dasa” follows (soḷasa).','dasasaddasmiṃ pare chasaddassa niccaṃ so-ādeso hotī ti ñāpanatthaṃ'),
377:('V','āgama','Inserción del niggahita al final de los numerales (vīsaṃ, tiṃsaṃ).','Insertion of the niggahita at the end of the numerals (vīsaṃ, tiṃsaṃ).','tāsaṃ saṅkhyāsaddānaṃ ante niggahītāgamo hotī ti ñāpanatthaṃ'),
378:('V','āgama','Inserción de ‘ti’ al final de los numerales (vīsati, tiṃsati).','Insertion of ‘ti’ at the end of the numerals (vīsati, tiṃsati).','tāsaṃ saṅkhyānaṃ ante tikārāgamo hotī ti ñāpanatthaṃ'),
379:('V','ādesa','Sustitución de ‘da’ y ‘ra’ de los numerales por ‘la’ (soḷasa, cattālīsaṃ).','Substitution of ‘da’ and ‘ra’ of the numerals by ‘la’ (soḷasa, cattālīsaṃ).','dakāra-rakārānaṃ lakārādeso hotī ti ñāpanatthaṃ'),
380:('V','ādesa','Sustitución de “dvi” por ‘bā’ cuando siguen “vīsati” y “dasa” (bāvīsati, bārasa).','Substitution of “dvi” by ‘bā’ when “vīsati” and “dasa” follow (bāvīsati, bārasa).','vīsati-dasa icc etesu dvisaddassa bādeso hotī ti ñāpanatthaṃ'),
381:('V','ādesa','Opcionalmente, sustitución de la ‘da’ de “dasa” por ‘ra’ tras “eka” y otros, en los numerales (ekārasa).','Optionally, substitution of the ‘da’ of “dasa” by ‘ra’ after “eka” and others, in numerals (ekārasa).','ekādito dasasaddassa dakārassa rakārādeso hoti saṅkhyāne vikappenā ti ñāpanatthaṃ'),
382:('V','ādesa','Opcionalmente, sustitución de la ‘da’ de “dasa” por ‘ra’ también tras “aṭṭha” y otros (aṭṭhārasa).','Optionally, substitution of the ‘da’ of “dasa” by ‘ra’ also after “aṭṭha” and others (aṭṭhārasa).','aṭṭhādito ca dasasaddassa dakārassa rakārādeso hoti saṅkhyāne vikappenā ti ñāpanatthaṃ'),
383:('V','ādesa','Opcionalmente, sustitución del final de “dvi”, “eka” y “aṭṭha” por ‘ā’ en los numerales (dvādasa, ekādasa, aṭṭhādasa).','Optionally, substitution of the end of “dvi”, “eka” and “aṭṭha” by ‘ā’ in numerals (dvādasa, ekādasa, aṭṭhādasa).','dvi eka aṭṭha icc etesam anto ākāro hoti saṅkhyāne vikappenā ti ñāpanatthaṃ'),
384:('V','paccaya','Aplicación de los sufijos ‘tha’ y ‘ṭha’ tras “catu” y “cha”, en el significado de ordinal (catuttha, chaṭṭha).','Application of the suffixes ‘tha’ and ‘ṭha’ after “catu” and “cha”, in the sense of an ordinal (catuttha, chaṭṭha).','catu cha icc etehi tha ṭha icc ete paccayā honti saṅkhyāpūraṇatthe ti ñāpanatthaṃ'),
385:('V','paccaya','Aplicación del sufijo ‘tiya’ tras “dvi” y “ti”, en el significado de ordinal.','Application of the suffix ‘tiya’ after “dvi” and “ti”, in the sense of an ordinal.','dvi ti icc etehi tiyapaccayo hoti saṅkhyāpūraṇatthe ti ñāpanatthaṃ'),
386:('V','ādesa','Sustitución de “dvi” y “ti” por ‘du’ y ‘ta’ cuando sigue ‘tiya’ (dutiya, tatiya).','Substitution of “dvi” and “ti” by ‘du’ and ‘ta’ when ‘tiya’ follows (dutiya, tatiya).','tiyapaccayasmiṃ dvi-tisaddānaṃ du-tādesā hontī ti ñāpanatthaṃ'),
387:('V','ādesa','Sustitución de “catuttha”, “dutiya” y “tatiya” con “aḍḍha” como miembro precedente por ‘aḍḍhuḍḍha’, ‘divaḍḍha’/‘diyaḍḍha’ y ‘aḍḍhatiya’.','Substitution of “catuttha”, “dutiya” and “tatiya” with “aḍḍha” as preceding member by ‘aḍḍhuḍḍha’, ‘divaḍḍha’/‘diyaḍḍha’ and ‘aḍḍhatiya’.','tesaṃ … catuttha-dutiya-tatiyasaddānaṃ aḍḍhasaddūpapadānaṃ upapadena saha aḍḍhuḍḍha-diyaḍḍh’-aḍḍhatiya icc ete ādesā hontī ti ñāpanatthaṃ'),
388:('V','lopa','De las palabras de igual forma dichas más de una vez queda una sola; las demás se eliden (ekasesa: purisā).','Of words of the same form said more than once only one remains; the others are elided (ekasesa: purisā).','sarūpānaṃ padabyañjanānaṃ ekaseso hoti asakin ti ñāpanatthaṃ'),
389:('V','ādesa','En la enumeración, sustitución de dos dieces … nueve dieces (tras el ekasesa) por ‘vī’, ‘ti’, ‘cattāra’, ‘paññā’, ‘cha’, ‘satta’, ‘asa’, ‘nava’ ante ‘yo’, y de ‘yo’ por ‘īsaṃ’, ‘āsaṃ’, ‘ṭhi’, ‘ri’, ‘ti’, ‘īti’, ‘uti’ (vīsaṃ … navuti).','In enumeration, substitution of two tens … nine tens (after the ekasesa) by ‘vī’, ‘ti’, ‘cattāra’, ‘paññā’, ‘cha’, ‘satta’, ‘asa’, ‘nava’ before ‘yo’, and of ‘yo’ by ‘īsaṃ’, ‘āsaṃ’, ‘ṭhi’, ‘ri’, ‘ti’, ‘īti’, ‘uti’ (vīsaṃ … navuti).','gaṇane gamyamāne dasassa dvi-ti-catu-pañca-cha-satta-aṭṭha-navakānaṃ katekasesānaṃ yathāsaṅkhyaṃ vī ti cattāra paññā cha satta asa nava icc ete ādesā honti yosu, yonañ ca īsaṃ āsaṃ ṭhi ri ti īti uti icc ete ādesā hontī ti ñāpanatthaṃ'),
390:('V','lopa + ādesa','Elisión de ‘tu’ del miembro precedente “catu” y, ocasionalmente, sustitución de la ‘ca’ inicial del miembro siguiente por ‘cu’ y ‘co’ (cuddasa, coddasa).','Elision of ‘tu’ of the preceding member “catu” and, occasionally, substitution of the initial ‘ca’ of the following member by ‘cu’ and ‘co’ (cuddasa, coddasa).','upapadassa catusaddassa gaṇane pariyāpannassa tulopo ca uttarapadassa ādicakārassa cu co ādesā honti navā ti ñāpanatthaṃ'),
391:('V','nipātana','Las palabras que no se explican por ninguna regla se realizan por nipātana.','Words not accounted for by any rule are established by nipātana.','… te nipātanā sijjhantī ti ñāpanatthaṃ'),
392:('V','paccaya','Aplicación del sufijo ‘ka’ tras “dvi” y otros, también en el significado de multiplicidad (dvikaṃ, tikaṃ); las formas se realizan por nipātana.','Application of the suffix ‘ka’ after “dvi” and others, also in the sense of multiplicity (dvikaṃ, tikaṃ); the forms are established by nipātana.','dvādito kapaccayo hoti anekatthe ti ñāpanatthaṃ'),
393:('V','ādesa','Ante ‘yo’, sustitución de «diez decenas» por ‘sataṃ’ y de «cien decenas» por ‘sahassaṃ’.','Before ‘yo’, substitution of “ten tens” by ‘sataṃ’ and of “a hundred tens” by ‘sahassaṃ’.','gaṇane pariyāpannassa … dasasaddassa sata-sahassādeso hoti yomhi vibhattimhī ti ñāpanatthaṃ'),
394:('V','nipātana','Los numerales superiores se forman multiplicando por diez (dasasahassaṃ, satasahassaṃ).','Higher numerals are formed by multiplying by ten (dasasahassaṃ, satasahassaṃ).','yāva tāsaṃ saṅkhyānaṃ uttari tāva dasaguṇitaṃ kātabban ti ñāpanatthaṃ'),
395:('V','nipātana','Los numerales que no tienen nombre establecido se forman con sus propios nombres (koṭi, pakoṭi …).','Numerals with no stated name are formed by their own names (koṭi, pakoṭi …).','yāsaṃ saṅkhyānam aniddiṭṭhanāmadheyyānaṃ rūpāni, tāni sakehi sakehi nāmehi nippajjante ti ñāpanatthaṃ'),
396:('V','lopa','Elisión de la ‘ṇ’ indicativa de los sufijos de derivado secundario.','Elision of the indicatory ‘ṇ’ of the secondary-derivative suffixes.','tesaṃ taddhitapaccayānaṃ ṇānubandhānaṃ ṇakāro lopam āpajjate ti ñāpanatthaṃ'),
397:('V','paccaya','Aplicación del sufijo ‘dhā’ en el significado de división (dvidhā).','Application of the suffix ‘dhā’ in the sense of division (dvidhā).','vibhāgatthe dhāpaccayo hotī ti ñāpanatthaṃ'),
398:('V','paccaya','Aplicación del sufijo ‘thā’ tras los pronombres en el significado de modo (tathā, yathā).','Application of the suffix ‘thā’ after pronouns in the sense of manner (tathā, yathā).','sabbanāmehi pakāravacanatthe thāpaccayo hotī ti ñāpanatthaṃ'),
399:('V','paccaya','Aplicación del sufijo ‘thaṃ’ tras “kiṃ” e “ima” en el significado de modo (kathaṃ, itthaṃ).','Application of the suffix ‘thaṃ’ after “kiṃ” and “ima” in the sense of manner (kathaṃ, itthaṃ).','kiṃ ima icc etehi pakāravacanatthe thaṃpaccayo hotī ti ñāpanatthaṃ'),
400:('V','vuddhi','Fortalecimiento de la vocal inicial (no seguida de consonante conjunta) cuando sigue un sufijo con ‘ṇ’ indicativa (ābhidhammiko, venateyyo).','Strengthening of the initial vowel (not followed by a conjunct) when a suffix with indicatory ‘ṇ’ follows (ābhidhammiko, venateyyo).','ādisarassa vā ādibyañjanassa vā asaṃyogantassa vuddhi hoti ṇakārānubandhasmiṃ paccaye ti ñāpanatthaṃ'),
401:('V','paṭisedha + āgama','‘i’ y ‘u’ iniciales no se fortalecen; en su lugar se inserta el fortalecimiento ‘e’, ‘o’ (veyyākaraṇo).','Initial ‘i’ and ‘u’ are not strengthened; instead the strengthening ‘e’, ‘o’ is inserted (veyyākaraṇo).','i u icc etesaṃ ādibhūtānaṃ mā vuddhi hoti, puna vuddhāgamo hoti ṭhāne ti ñāpanatthaṃ'),
402:('V','ādesa + āgama','Sustitución de ‘i’ y ‘u’ iniciales por ‘ā’, e inserción de ‘ri’ (ārisyaṃ, ājjavaṃ).','Substitution of initial ‘i’ and ‘u’ by ‘ā’, and insertion of ‘ri’ (ārisyaṃ, ājjavaṃ).','i u icc etesaṃ āttañ ca hotī ti ñāpanatthaṃ … caggahaṇena rikārāgamo ca hoti'),
403:('V','dīgha + rassa','A veces, alargamiento o acortamiento de las vocales inicial, media y final, cuando siguen sufijos y cuando no.','Sometimes, lengthening or shortening of the initial, middle and final vowels, when suffixes follow and when they do not.','kvaci ādi-majjh’-uttarānaṃ dīgha-rassā honti paccayesu ca apaccayesu cā ti ñāpanatthaṃ'),
404:('V','vuddhi + lopa + āgama + vikāra + viparīta + ādesa','En esos lugares (inicial, medio, final), a veces, fortalecimiento, elisión, inserción, cambio, inversión y sustitución, según la palabra del Victorioso.','In those places (initial, middle, final), sometimes, strengthening, elision, insertion, change, inversion and substitution, as the Word of the Victorious One requires.','tesu ādi-majjh’-uttaresu kvaci vuddhi-lopāgama-vikāra-viparītādesā hontī ti ñāpanatthaṃ'),
405:('S','','‘ā’, ‘e’ y ‘o’ son el fortalecimiento (vuddhi) de ‘a’, de ‘i’/‘ī’ y de ‘u’/‘ū’ respectivamente.','‘ā’, ‘e’ and ‘o’ are the strengthening (vuddhi) of ‘a’, of ‘i’/‘ī’ and of ‘u’/‘ū’ respectively.','a-ivaṇṇ’-uvaṇṇānaṃ ā-e-o vuddhiyo hontī ti ñāpanatthaṃ'),
})
VUD_ES='Etiqueta «vuddhi» provisional, pendiente del IEBH: vuddhi no está entre las ocho clases de vidhi del Glosario de Nandisena, pero Kaccāyana la nombra aparte en §404 y §405, y Niruttidīpanī la cuenta como clase propia de operación («lopo, dīgho, rasso, vuddhi, ādeso, āgamo, dvibhāvo, vipallāso»).'
VUD_EN='The “vuddhi” label is provisional, pending the IEBH: vuddhi is not among the eight kinds of vidhi in Nandisena’s Glossary, but Kaccāyana names it separately in §404 and §405, and the Niruttidīpanī counts it as an operation of its own (“lopo, dīgho, rasso, vuddhi, ādeso, āgamo, dvibhāvo, vipallāso”).'
UNIV_ES='Uno de los cuatro suttas universales de Kaccāyana (nota 36 de la traducción del capítulo; U Sīlānanda los llama «universal suttas» y también «nipātana suttas», clases ch5-7 y ch7-5).'
UNIV_EN='One of Kaccāyana’s four universal suttas (note 36 of the chapter translation; U Sīlānanda calls them “universal suttas” and also “nipātana suttas”, classes ch5-7 and ch7-5).'
NOTAS.update({
356:('Por «ca», Rū 381 y Nyāsa extienden el sufijo al significado de «bueno para eso» (upādāniyā). Determinación: vidhi — paccaya.','By “ca”, Rū 381 and the Nyāsa extend the suffix to the sense “good for that” (upādāniyā). Determination: vidhi — paccaya.'),
360:('Por «tu», Rū 387 añade los sufijos ‘ttana’, ‘ṇeyya’, etc. Determinación: vidhi — paccaya.','By “tu”, Rū 387 adds the suffixes ‘ttana’, ‘ṇeyya’, etc. Determination: vidhi — paccaya.'),
364:('Por «ca», Rū 398 añade los sufijos ‘so’, ‘ila’, ‘va’, ‘āla’, etc. (sumedhaso, lomaso). Determinación: vidhi — paccaya.','By “ca”, Rū 398 adds the suffixes ‘so’, ‘ila’, ‘va’, ‘āla’, etc. (sumedhaso, lomaso). Determination: vidhi — paccaya.'),
377:('Sin correspondencia en Rūpasiddhi (número «0» en el capítulo; pendiente §7 de docs/capitulo-5/pendientes-taddhita.md). Nyāsa sí lo comenta. Determinación: vidhi — āgama.','No counterpart in the Rūpasiddhi (number “0” in the chapter; open item §7 of docs/capitulo-5/pendientes-taddhita.md). The Nyāsa does comment on it. Determination: vidhi — āgama.'),
388:('Nyāsa solo dice «ekaseso hoti»; Rū 68 precisa la operación: queda una sola y las demás se eliden («aññe lopam āpajjante»). Determinación: vidhi — lopa.','The Nyāsa only says “ekaseso hoti”; Rū 68 states the operation: one remains and the others are elided (“aññe lopam āpajjante”). Determination: vidhi — lopa.'),
390:('Dos vidhis. Lectura de Nandisena: «catu» es el miembro precedente y la ‘ca’ está al comienzo del miembro siguiente (decisión del IEBH, 2026-09-13; la variante de Rūpasiddhi queda en la nota 31 de la traducción). Determinación: vidhi — lopa + ādesa.','Two vidhis. Nandisena’s reading: “catu” is the preceding member and the ‘ca’ is at the beginning of the following member (IEBH decision, 2026-09-13; the Rūpasiddhi variant is kept in note 31 of the translation). Determination: vidhi — lopa + ādesa.'),
391:(UNIV_ES+' La vutti enumera los ámbitos: letras, género, nombres, compuestos, derivados, verbos, números, kāraka, sandhi, pakati, vuddhi, lopa, āgama, vikāra, viparīta, inflexiones. Rū lo hace regir los suttas siguientes («ti vattate», antes de Rū 417 = §395). Etiqueta «nipātana», no una de las ocho (decisión del IEBH, 2026-10-01). Determinación: vidhi — nipātana.',UNIV_EN+' The vutti lists its domains: letters, gender, nouns, compounds, derivatives, verbs, numbers, kāraka, sandhi, pakati, vuddhi, lopa, āgama, vikāra, viparīta, inflections. The Rūpasiddhi has it govern the following suttas (“ti vattate”, before Rū 417 = §395). Label “nipātana”, not one of the eight (IEBH decision, 2026-10-01). Determination: vidhi — nipātana.'),
392:('La vutti añade «nipātanā sijjhanti»: las formas se rematan por el §391. Determinación: vidhi — paccaya.','The vutti adds “nipātanā sijjhanti”: the forms are completed by §391. Determination: vidhi — paccaya.'),
393:('Rū 415 lo llama nipātana para la elisión de ‘yo’ («iminā nipātanena yolopo»); Nyāsa, sustitución. Determinación: vidhi — ādesa.','Rū 415 calls it a nipātana for the elision of ‘yo’ (“iminā nipātanena yolopo”); the Nyāsa, a substitution. Determination: vidhi — ādesa.'),
394:('No prescribe ninguna de las ocho operaciones: fija cómo se forman los numerales superiores, que se rematan por nipātana (§391). Determinación: vidhi — nipātana (decisión del IEBH, 2026-10-01).','It prescribes none of the eight operations: it fixes how higher numerals are formed, completed by nipātana (§391). Determination: vidhi — nipātana (IEBH decision, 2026-10-01).'),
395:('Rū 417: «nipaccante»; rige aquí el §391 («“Yad anupapannā nipātanā sijjhantī” ti vattate»). Determinación: vidhi — nipātana (decisión del IEBH, 2026-10-01).','Rū 417: “nipaccante”; §391 governs here (“‘Yad anupapannā nipātanā sijjhantī’ ti vattate”). Determination: vidhi — nipātana (IEBH decision, 2026-10-01).'),
400:(VUD_ES+' Determinación: vidhi — vuddhi (provisional).',VUD_EN+' Determination: vidhi — vuddhi (provisional).'),
401:('Primera parte, interdicción de la vuddhi («mā vuddhi»); segunda, inserción del fortalecimiento («vuddhāgamo», Rū 375: «ekāravuddhāgamo»). Determinación: vidhi — paṭisedha + āgama.','First part, prohibition of vuddhi (“mā vuddhi”); second, insertion of the strengthening (“vuddhāgamo”, Rū 375: “ekāravuddhāgamo”). Determination: vidhi — paṭisedha + āgama.'),
402:('Por «ca», inserción de ‘ri’ (Rū 377, Nyāsa). Determinación: vidhi — ādesa + āgama.','By “ca”, insertion of ‘ri’ (Rū 377, Nyāsa). Determination: vidhi — ādesa + āgama.'),
403:(UNIV_ES+' Determinación: vidhi — dīgha + rassa.',UNIV_EN+' Determination: vidhi — dīgha + rassa.'),
404:(UNIV_ES+' Se marcan las seis operaciones que nombra; «vikāra» (cambio) y «viparīta» (inversión) no son de las ocho (decisión del IEBH, 2026-10-01); «vuddhi», provisional. Determinación: vidhi — vuddhi + lopa + āgama + vikāra + viparīta + ādesa.',UNIV_EN+' The six operations it names are marked; “vikāra” (change) and “viparīta” (inversion) are not among the eight (IEBH decision, 2026-10-01); “vuddhi”, provisional. Determination: vidhi — vuddhi + lopa + āgama + vikāra + viparīta + ādesa.'),
405:('La traducción publicada y U Sīlānanda (clase ch5-7, ~80:00: «ā, e, o are called vuddhi») lo leen como definición. Rū 365 le da además una función de vidhi: la repetición de «vuddhi» sirve para el fortalecimiento del miembro siguiente («uttarapadavuddhibhāvatthaṃ»: negamajānapadā). Clasificación provisional, pendiente del IEBH junto con la etiqueta «vuddhi». Determinación: saññā (provisional).','The published translation and U Sīlānanda (class ch5-7, ~80:00: “ā, e, o are called vuddhi”) read it as a definition. Rū 365 also gives it a vidhi function: repeating “vuddhi” serves the strengthening of the following member (“uttarapadavuddhibhāvatthaṃ”: negamajānapadā). Provisional, pending the IEBH together with the “vuddhi” label. Determination: saññā (provisional).'),
})
for n,(tipo,vidhi,es,en,ny) in R.items():
    ru_es,ru_en=ru_txt(RU[n])
    e={'tipo':tipo,'vidhi':vidhi,'op':{'en':N(en),'es':N(es)},
       'base':{'ru':{'en':N(ru_en),'es':N(ru_es)},'nyasa':{'en':N(f'“{ny}”.'),'es':N(f'«{ny}».')}}}
    if n in NOTAS: e['nota']={'es':N(NOTAS[n][0]),'en':N(NOTAS[n][1])}
    S[str(n)]=e
V=D['vidhis']
V['vuddhi']={'es':'fortalecimiento (no es una de las ocho; provisional)','en':'strengthening (not one of the eight; provisional)','fuera':True}
V['vikāra']={'es':'cambio (no es una de las ocho)','en':'change (not one of the eight)','fuera':True}
V['viparīta']={'es':'inversión (no es una de las ocho)','en':'inversion (not one of the eight)','fuera':True}
V['nipātana']={'es':'formación por nipātana (no es una de las ocho)','en':'formation by nipātana (not one of the eight)','fuera':True}
if not any(c['clave']=='taddhita' for c in D['capitulos']):
    D['capitulos'].append({'clave':'taddhita','md':'05-taddhita-kappa','desde':344,'hasta':405,'pali':'Taddhita-Kappa'})
D['version']='0.4'
D['nota_version']={'es':'Se añade el Taddhita-Kappa (§344–§405). Contiene ya los capítulos 1 a 5.','en':'Adds the Taddhita-Kappa (§344–§405). Now covers chapters 1 to 5.'}
json.dump(D,open(P,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print(len(S), len(R))
